### ISSUE TITLE
Proposal: React Navigation Vs React Native Flux Router / React Router

### ISSUE THREAD

**Issue by christopherhein** [react-everywhere/re-start#14]
Seems like the new https://github.com/react-community/react-navigation project could replace the need for the multiple handling of navigation in https://github.com/amoghbanta/reactNativeEverywhere/tree/master/src web integration is documented here - https://reactnavigation.org/docs/guides/web 

Still new but curious if this would help reduce duplication. As well redux integration seems to flow a bit better than with react-native-flux-router

Thoughts?

**Comment by amoghbanta** [comment]
Hi @christopherhein, I came across react-navigation couple of days back, haven't tried it yet but it is in the near plan to test it for web and native using  an all common code base. I completely agree that it  "could replace the need for the multiple handling of navigation" and reduce the duplication. Seems theoretically perfect to me  but i could comment on it better once I give it a try.

**Comment by kkszysiu** [comment]
For now it doesn't work so good.

They web implementation is very limited for now. I'm trying to do something about it but so far no success.

That's the differences:
https://github.com/react-community/react-navigation/blob/master/src/react-navigation.js
https://github.com/react-community/react-navigation/blob/master/src/react-navigation.web.js

Without StackNavigator/TabNavigator it seems to be very limited.
I would love to have it.

**Comment by christopherhein** [comment]
Ah sweet, thanks for the info!

**Comment by kkszysiu** [comment]
After some tweaks I'm able to run StackNavigator :)
It should work the same on both Android, iOS and web.

The example from web:
![screen capture on 2017-01-29 at 23-17-38](https://cloud.githubusercontent.com/assets/70684/22408472/ac4a6cc2-e679-11e6-91e1-9d5425ec0d05.gif)

But TabNavigator is really what I desire here.

I will try to push some example how to implement it when I make some code cleanup 👍

**Comment by christopherhein** [comment]
Oh should I reopen @kkszysiu ?

**Comment by ppsreejith** [comment]
@kkszysiu , how did you get the css to work? Changing the react-navigation.web.js file allowed me to use StackNavigator but the css is all broken

**Comment by christopherhein** [comment]
@kkszysiu did you do this in a fork somewhere? wanted to check out what was required to get it working

**Comment by fotiDim** [comment]
I guess this should be reopened as react-navigation is the way to go

**Comment by fotiDim** [comment]
@amoghbanta Any update on this?

**Comment by amoghbanta** [comment]
hey @fotiDim, so I've working on a complete rewrite of react-native-everywhere. The update on this is that react-router guys released v4 and that is exactly what fits our requirement. My aim is to keep it more of plug and play where in you can just replace react-router with react-navigation if you prefer that. It'll be out in a couple of days.

**Comment by fotiDim** [comment]
@amoghbanta any insights to share on where react navigation fell short?

**Comment by ajostergaard** [comment]
@amoghbanta - great work and thanks!!! Any news on the rewrite?

**Comment by amoghbanta** [comment]
hey @ajostergaard, [this](https://github.com/amoghbanta/react-native-everywhere/tree/template) branch is where the rewrite is going on.
Now, since react-native supports [templates](https://github.com/facebook/react-native/pull/12548), so this project will be more of a template(supporting multiple platforms) with some additional scripts. No more git cloning. We are also working on a component library which would support multiple platforms too.

**Comment by amoghbanta** [comment]
hey @fotiDim, its just that react-router's API was an exact match/requirement for us. I personally haven't played much with react-navigation so I can't comment. As i said earlier, it would be more of a plug and play thing, so you can use the one you feel is right for your project.

**Comment by ajostergaard** [comment]
Thanks @amoghbanta. How mature is the template? Ready for a relative beginner to use for an app?

**Comment by amoghbanta** [comment]
Template is ready to be used, you guys can give it a try and as of now it works on react-router v4.
Closing this one.
