### ISSUE TITLE
Status of templates?

### ISSUE THREAD

**Issue by piranna** [react-everywhere/re-start#19]
Readme says that the refactor to using templates would be ready in two weeks, but it was two months ago... Could you be able to give an update of the progress and an stimate time for it? Is it ready to start a new project although it's not in the master branch?

**Comment by amoghbanta** [comment]
Hey @piranna,
I tested the template on all the platforms and it does the work. There is still a lot of work that needs to be done but its at a stage to get you started.

**Comment by piranna** [comment]
Oh cool, thanks! :-D
