### ISSUE TITLE
Add support for Electron

### ISSUE THREAD

**Issue by piranna** [react-everywhere/re-start#25]
Add support for Electron as a target platform. According to [this tutorial](https://www.twilio.com/blog/2015/12/getting-started-with-electron-building-a-desktop-chat-app.html) seems Electron apps can be heavily based on the web ones, being main difference the usage of non-relative-protocol URLs, that could be easily checked and change before building the Electron bundle.

**Comment by amoghbanta** [comment]
Hi @piranna,
I've been working on this lately, please check the electron branch. Plan is to add support to master by this weekend.

**Comment by piranna** [comment]
Cool! I'll take a look in the next days :-)

**Comment by piranna** [comment]
Is there any way to update a project? Or should I apply these changes by hand?

**Comment by amoghbanta** [comment]
as of now, you have to do it by hand but there needs to be a way to do it. I'll look into it.

**Comment by piranna** [comment]
Any update on this?

**Comment by christopherhein** [comment]
I see the `README.md` has been updated to reflect the electron changes and the code seems to be there but the `npm` package doesn't include it.

Looks like using file path for `--template` isn't building correctly. Not sure if that is intended. I get a lot of `incorrect peer dependency XYZ` as well from file path off `master` I get `cannot lstat(node_modules/re-start)`

**Comment by piranna** [comment]
Dependencies are a bit outdated, I'm trying to have them up-to-date on my project but it's not possible to doing so with all of them. Also `peerDependency` problems seems to be common, there's a lot of dependencies that themselves depend on several versions. I think it would be a difficult one to fix.

**Comment by amoghbanta** [comment]
Hey,
sorry for the delay, i'll update all the dependencies soon after react-native releases their version compatible with react 16 (that'll be react-native 0.49 I think) and also update the npm package with electron support.

**Comment by piranna** [comment]
Ok, thanks. Currently I have been keeping updated some of the dependencies, maybe I could be able to do a pull-requests with them if you want...

**Comment by amoghbanta** [comment]
That would be great :)

**Comment by piranna** [comment]
> That would be great :)

I'll try to find some time to do it, there are some other fixed that need to be done too :-)

**Comment by emirotin** [comment]
Just encountered the same when trying out this project (which I want to use primarily for Electron now, and for native later).
react-native has 0.49.3 with React 16 now

**Comment by piranna** [comment]
Pull-request for React 16 are welcome :-)

**Comment by emirotin** [comment]
I'm experienced with React but am very new to react-native and all flavors of it. So cannot help here unfortunately, was hoping for this proj to help me get started :)

**Comment by amoghbanta** [comment]
Hey @emirotin 
Have a look at #29. This will be merged into master soon.

**Comment by emirotin** [comment]
Nice @amoghbanta let me try it out!

**Comment by amoghbanta** [comment]
Master now has the support for electron and I've published it to npm.
Closing this one.
