### ISSUE TITLE
Several problems

### ISSUE THREAD

**Issue by gretzky** [react-everywhere/re-start#37]
There are no commands inside `package.json` to run the windows or electron builds.

There's also no documentation regarding the prerequisites to run the iOS or Android builds in development.

The amount of dependencies is huge, and there's no way to bundle or cache them provided.

Pretty disappointing that this doesn't actually run what it says it can 😕

**Comment by piranna** [comment]
> There are no commands inside package.json to run the windows or electron builds.

It would be good if they could be added so there's no need to use external tools to run all that's possible to do with re-start. Would you like to do a pull-request for that? :-)


> The amount of dependencies is huge, and there's no way to bundle or cache them provided.

Project is huge... @amoghbanta [was planning to use react-scripts](https://github.com/react-everywhere/re-start/pull/31#issuecomment-333578983), but seems to be busy lately... :-/

**Comment by gretzky** [comment]
I'd love to contribute. I'll see what I can do to help.
