### ISSUE TITLE
Sponsors section?

### ISSUE THREAD

**Issue by piranna** [react-everywhere/re-start#38]
The commits I have done recently on `re-start` is related to my work on http://www.quantum-ba.com/, so what about adding a section of "sponsors" and/or "companies using re-start" so we give them some credit? :-)

**Comment by amoghbanta** [comment]
Sure!
that would be awesome 😄

**Comment by piranna** [comment]
Done, I wanted to do a pull-request from online editor and since I had push requests it did it directly on master, sorry :-P
