### ISSUE TITLE
Please consider a license change to MIT

### ISSUE THREAD

**Issue by andrioid** [react-everywhere/re-start#39]
Please consider changing the license from GPL to MIT (as React and React Native)

Since we'd be using this template as a basis for a project, I'm pretty sure anything you'd work on from it, would inherit the GPL license. Hence, this is not usable for companies that aren't willing to open-source their apps.

I might be overly cautious and I don't have a legal degree, but this would ease my nerves.

**Comment by piranna** [comment]
Just to clarify, GPL license only affect to the tool, not the generated products. In this case, the template can be GPL, but the code of the project bootstrapped from it doesn't need to be so. A different thing would be if you do your own template based on this one, in that case the GPL license force that your custom template is also licensed as GPL.

**Comment by andrioid** [comment]
Sure, and I get why GPL was picked. I'd just rather not have the legal uncertainty.  If a GPL tool generates code, isn't the code also GPL? And anything you would build on that, would inherit GPL, right?

https://www.gnu.org/licenses/gpl-faq.en.html

If you read the part about Emacs and Bison, they say that it doesn't inherit the GPL license, because of the input is the user. If the input is a tool, then what?

**Comment by piranna** [comment]
> If a GPL tool generates code, isn't the code also GPL?

I warrant you that not :-) I can't be able to pick you to some exact place to confirm that, but take for example the case of GCC compiler, that's also with GPL license and the compiled programs don't need too :-D


> And anything you would build on that, would inherit GPL, right?

If you do a derivated template, then yes, It needs to be GPL too. Other thing is if this tool would be LGPL, then no, the derivated template can be any license you want, only would be GPL the change you did to the parent project (this one).


> If you read the part about Emacs and Bison, they say that it doesn't inherit the GPL license, because of the input is the user. If the input is a tool, then what?

I would say this is the same situation, but if you are not sure, you can still ask for a lawyer about that or wait until @amoghbanta says something about the change of license...

**Comment by amoghbanta** [comment]
Totally agree with @piranna, this was anyways on the to-do list for some time. re-start now MIT licensed. 😄 
Closing this one.
