### ISSUE TITLE
Native routing example

### ISSUE THREAD

**Issue by mitajunior** [react-everywhere/re-start#41]
How can move from one screen to another? 

I have tried 
```js this.props.router.push('/home') ```

But nothing is working

**Comment by amoghbanta** [comment]
The template uses react-router out of the box. You can find the documentation [here](https://reacttraining.com/react-router/native/guides/philosophy). I don't think that programmatic routing is supported in their latest version.

**Comment by mitajunior** [comment]
The routing part is not very clear, they should probably include more of that in the documentation...added [react-native-router-flux](https://github.com/aksonov/react-native-router-flux) and it works perfectly

**Comment by amoghbanta** [comment]
How do you manage your routing for the web?
I don't think **react-native-router-flux** will work with **react-native-web**.
