### ISSUE TITLE
React-Native Testing

### ISSUE THREAD

**Issue by ReyHaynes** [react-everywhere/re-start#44]
First off, I want to say, great template.

Unfortunately this does not test well. Even simply running `yarn run test` with a new initiated project will fail even though the build will run. Is there a way to get past that?

**Comment by piranna** [comment]
I'm interested on the testing issue, could you be able to explain yourself? Maybe `re-base` template is better suited for that?

**Comment by ReyHaynes** [comment]
After going through the install, running `yarn run test` in general fails the rendering stage.

![image](https://user-images.githubusercontent.com/4911931/32510411-87cc4c44-c3be-11e7-8d83-09b60c66e349.png)

The error is pretty obvious for a react-native build test, but even removing `window` will lead a line of other errors.

Would love to know if that is just a thing that isn't avoidable because jest testing is pretty important.

**Comment by piranna** [comment]
Maybe could you be able to try to fix the errors and do a pull-request?

**Comment by ReyHaynes** [comment]
That'd be great @piranna!
