### ISSUE TITLE
index.android.js and ios missing

### ISSUE THREAD

**Issue by albertparedandan** [react-everywhere/re-start#45]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **this template** file a Github issue.
  * For issues regarding react-native, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately or visit react-native's [issues page](https://github.com/facebook/react-native/issues).

### Step 2: Describe your environment

  * **template version** : (latest)
  * **react-native version**: (2.0.1)
  * **OS** : ubuntu 16.04 LTS
  * **Platform causing error**: (android/ios/web/electron)
  
### Step 3: Describe the problem (try to include screenshots):
when i run react-native init projectname --template re-start, the files are generated but index.android.js and index.ios.js is missing. furthermore when i cd projectname and try to run the node scripts/devdependencies.js, it runs successfully until the end where it is trying to remove devdependencies and it says that devdependencies does not exist on my project directory.
also, when i try to run react-native run-android it just says "unable to load script from assessts index.android.budle make sure your bundle is packaged correctly or you're running a packager server" on my device after running the apk.

#### Steps to reproduce:

  1. react-native init projectname --template re-start
  2. npm install, node scripts/devDependencies.js
  3. react-native run-android

**Comment by mndvn** [comment]
Hi Albert, They are not missing. In the React-Native 0.51, There is only one index.js file for ios, android and web. This template supports React 16 and React Native 0.51
