### ISSUE TITLE
Use rimraf instead of rm in additionalDependencies.js

### ISSUE THREAD

**Issue by wintercounter** [react-everywhere/re-start#48]
### Step 1: Are you in the right place?
Yes

### Step 2: Describe your environment

  * **template version** : 0.3.2
  * **react-native version**: irrelevant
  * **OS** : Windows
  * **Platform causing error**:  irrelevant
  
#### Steps to reproduce:

  1. Install the application
  2. Run `additionalDependencies.js`
  3. No such command as `rm`
  
#### Observed Results:

```
'rm' is not recognized as an internal or external command,
operable program or batch file.
```
  
#### Expected Results:

Shouldn't fail.
  
#### Relevant Code/Commands:

Use `rimraf` instead of relying on `rm`. I've tried, it works fine.

**Comment by piranna** [comment]
Can you provide a pull-request?

**Comment by amoghbanta** [comment]
Thank you for reporting @wintercounter.
I'll fix this and other open bugs tomorrow.
