### ISSUE TITLE
where is webpack config?

### ISSUE THREAD

**Issue by amorenew** [react-everywhere/re-start#49]
I want to use cross-platform components from react native web
https://github.com/react-native-web-community
but I don't know where is the webpack config file? so  I can add alias to it

**Comment by amorenew** [comment]
I found it in node_modules\react-scripts\config
but if I removed node_modules for any reason I will lost my alias for react native web components
any solution so I don't lost my changes in the webpack config?

**Comment by piranna** [comment]
If you want to customize webpack config, execute `react-scripts eject`, and all the react-scripts internal configs will be set at project level, so react-scripts will not work anymore.
