### ISSUE TITLE
`npm run build` fails

### ISSUE THREAD

**Issue by kevnk** [react-everywhere/re-start#5]
`$ npm run build`

```
> babel-node tools/build.js

sh: babel-node: command not found
```

`$ npm install -g babel-cli` solves that. But now there's no `tools/build.js` file

**Comment by amoghbanta** [comment]
hey @kevnk
you need babel-cli in global scope for babel-node.
`npm i -g babel-cli`
I have also added the build script. Can you please check now.

**Comment by amoghbanta** [comment]
It should not now, after the rewrite. Please give it a try.
