### ISSUE TITLE
Firebase Host

### ISSUE THREAD

**Issue by amorenew** [react-everywhere/re-start#50]
I tried firebase host and it is very helpful.
Just 1 command  "firebase deploy" and my react code will be online as a webpage.
I think it could be a nice feature.

**Comment by amoghbanta** [comment]
Hey @amorenew, I have not tried firebase host but tried out surge.sh, which does something similar. This sounds good. You can enhance re-base and create a new template and send a PR for the same. 😄

**Comment by amorenew** [comment]
@amoghbanta is surge have published history like firebase host?
![image](https://user-images.githubusercontent.com/2842459/35374618-bf4634da-01b4-11e8-8ad4-9cf162056675.png)
