### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by jaulz** [react-everywhere/re-start#51]
It seems that this project is abandoned. Any plan on continuing at some point in the future?
Anyway, great work so far and thanks a lot!

**Comment by piranna** [comment]
I'm waiting for some answer from @amoghbanta, but it's not answering messages. Maybe he's having some problems. What about working on a fork and later merge it back when he goes online again? :-)

**Comment by amoghbanta** [comment]
Hey @jaulz and @piranna, I was stuck somewhere and couldn't find out any time to work on this. I apologize for abandoning this project meanwhile. I have made some updates and fixes recently. Do check them out. Everything would be on track from now on.
