### ISSUE TITLE
`react-native-web` version is too old

### ISSUE THREAD

**Issue by geminiyellow** [react-everywhere/re-start#61]
### Environment

  * **template name** : re-start
  * **template version** : (0.3.2)
  * **react-native version**: (0.55.2)
  * **react-native-web version**: (0.1.13)
  * **OS** : (osX)
  * **Platform causing error**: (web)
  
### The problem

```
$ ncu
> react-native-web                                 0.1.13  →         0.6.0 
```

#### Expected Results:

Please update to the latest version. thank you.

**Comment by piranna** [comment]
I confirm latests `react-native-web` works flawlessly with `re-start`, could you be able to provide a pull-request for that? :-)

**Comment by geminiyellow** [comment]
oh, really ? here #62
