### ISSUE TITLE
undefined is not an object (evaluating in xxx.xxx) in safari.

### ISSUE THREAD

**Issue by yadavsachin** [react-everywhere/re-start#64]
xxx.xxx is works well in chrome and IE

**Comment by yadavsachin** [comment]
I have function called 
isCustomerDataAvailable(){
return this.data || IsNull(Data.Customer)
}

Data.Customer is basically return as "object" in chrome and IE
Strange thing is in safari also it returns me as "object" but sometimes it throws me error as below.
message: "undefined is not an object (evaluating 'Data.Customer')"

**Comment by yadavsachin** [comment]
I found similar thread around this. Do I need try similar thing in my case
https://github.com/OneSignal/OneSignal-Website-SDK/issues/295

**Comment by piranna** [comment]
Yes, you should do a similar fix, seems `Data` is not defined, whatever it is.
