### ISSUE TITLE
UI library for cross platform

### ISSUE THREAD

**Issue by Alphapage** [react-everywhere/re-start#65]
Hello,

I can't find any info about compatible UI library for react-everywhere.
Do you only use style to customize your ui ?

Thank you in advance for your answers.

**Comment by piranna** [comment]
There are several of them, for example I have been sucessful using https://github.com/xotahal/react-native-material-ui. Anything that don't make use of native components should work, and as a rule of thumb, if it's compatible with `react-native-web` it probably will run everywhere.
