### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by gustavo-depaula** [react-everywhere/re-start#72]

**Comment by piranna** [comment]
I'm maintaining it, but don't have permissions to publish on `npm`... I'm thinking about renaming the project and publish it myself.

@amoghbanta, can you give us some light here, please? :-)

**Comment by amoghbanta** [comment]
Hey @piranna, i have not had time to maintain this for some time now but have plans to come back to it soon. I'll add you to the npm organization. Thank you for all your efforts 😄

**Comment by piranna** [comment]
You are welcome! :-D Thanks to you, I'm currently using it in several projects :-)

**Comment by gustavo-depaula** [comment]
Thanks for the responses! Closing the issue...
